### ISSUE TITLE
joselio

### ISSUE THREAD

**Issue by joseliobeze** [flaviomicheletti/github-foo#3]
"aqui não tem problema"

**Comment by flaviomicheletti** [comment]
E aí Joselio, tudo bem ?

Não é bem assim! De vez em qaundo aparece uns problemas para a gente resolver.

rssssss

abs.

**Comment by flaviomicheletti** [comment]
This is an [example link](http://example.com/).

**Comment by flaviomicheletti** [comment]
This is an [example link](http://example.com/).
